### ISSUE TITLE
Plugin does not handle multi-root workspace

### ISSUE THREAD

**Issue by benjaminhdavis** [Ericsson/CodecheckerVSCodePlugin#113]
I'm using this plugin on a multi-root workspace with a configuration like:

folder1/compile_commands.json
folder2/compile_commands.json

If I modify C code in `folder2/something.c`  the CodeChecker analyze will run using `folder1/compile_commands.json`

**Comment by dkrupp** [comment]
I think this feature is best supported by the CodeChecker tooling itself, because then it would give the same look and feel for command line users:
https://github.com/Ericsson/codechecker/issues/3708

**Comment by dkrupp** [comment]
If the plugin is used with CodeChecker 6.22.0 it does handle multi-root workspace.
