### ISSUE TITLE
Skip suppressed reports

### ISSUE THREAD

**Issue by csordasmarton** [Ericsson/CodecheckerVSCodePlugin#20]
Suppressed reports are not skipped for now. In the next CodeChecker release (`6.18.0`) we will refactor the json output format and we will also solve the problem to skip suppressed reports in json format. After this release we will rely on this json output instead of parsing plist files.

**Comment by dkrupp** [comment]
The new JSON output format is complete with this patch: 

https://github.com/Ericsson/codechecker/commit/85dd52dc8f4d47fcf26419fcb44de1ff2a58924f

the outptut of the parse command has a new json format.
