### ISSUE TITLE
bug steps inserted to the wrong level in the problems tree

### ISSUE THREAD

**Issue by dkrupp** [Ericsson/CodecheckerVSCodePlugin#49]
For example "enter call from args_string" step belongs to the "dreference of null pointer bug"
These steps should be under the respective bug report and not directly under the file in the tree.

![image](https://user-images.githubusercontent.com/8030953/151153761-e077d84f-4bc3-424a-bfc3-57ff3811faf9.png)

**Comment by Discookie** [comment]
I don't believe grouping in the Problems tab is possible like this.
The only items that can belong to a Diagnostic are the links that are displayed there.
These are only marked with a small ... at the target location in the code, and they don't support underlining ranges.

For a detailed view, the Reports in current file section is the one we have better control over. The Problems are only meant to be the highlights in the editor.
