### ISSUE TITLE
Publish CodeChecker plugin to the marketplace

### ISSUE THREAD

**Issue by csordasmarton** [Ericsson/CodecheckerVSCodePlugin#5]
- [x] Publish the plugin to the official marketplace (https://marketplace.visualstudio.com/).
- [ ] Extend the documentation how to install and use this plugin.
- [ ] Create a github action to automatically publish the plugin to the market place when a new version is released.

**Comment by Discookie** [comment]
The VSCode API docs has a handy guide for publishing the extension:
https://code.visualstudio.com/api/working-with-extensions/publishing-extension

There's a guide for automatic publishing with Github Actions as well:
https://code.visualstudio.com/api/working-with-extensions/continuous-integration#github-actions
