### ISSUE TITLE
Detect `compile_commands.json` in project root.

### ISSUE THREAD

**Issue by steakhal** [Ericsson/CodecheckerVSCodePlugin#51]
In my project, I use `clangd`, which can detect the `compile_commands.json` symlink in my project root directory, which will actually point to the actual json within a separate build directory.
For some reason, this plugin did not recognize this and explicitly asked to the  `compile_commands.json` in a popup window.

My question is why could not detect my `compile_commands.json` out of the box - similarly how `clangd` could.

**Comment by csordasmarton** [comment]
I created a patch which will try to find compilation database automatically in the following places:
- `$WORKSPACE_DIR/.codechecker`
- `$WORKSPACE_DIR`
- `$WORKSPACE_DIR/build`

with the following names:
- `compile_commands.json`
- `compile_cmd.json`

**Comment by Discookie** [comment]
The fix also follows symlinks, so your setup should work even if `compile_commands.json` is in a different folder.
