### ISSUE TITLE
Don't popup the "CodeChecker: analysis in progress..."

### ISSUE THREAD

**Issue by steakhal** [Ericsson/CodecheckerVSCodePlugin#61]
Please don't create an unclosable popup stating "CodeChecker: analysis in progress..."
![image](https://user-images.githubusercontent.com/6280485/151386831-5ce7dfec-ab88-455b-8234-a801900dcdb3.png)

This is really annoying. And it's open for about 5 minutes for the largest translation units; since the analysis takes so much time.
That being said, I hope we cancel the background analysis if we saved some changes.

IMO we should just remove this popup completely since the user already knows that an analysis is in progress here:
![image](https://user-images.githubusercontent.com/6280485/151386872-397fb65d-3c24-45bf-9939-5e0be0db1352.png)

Alternatively, give an option or something to make it disappear.

**Comment by csordasmarton** [comment]
@steakhal I totally agree with you that it is really annoying on large projects. I created to patch to remove this pop-up window (#64) and also added an extra tree item to be able to stop the analysis from the GUI:
![image](https://user-images.githubusercontent.com/6695818/151764188-cca705aa-e4c0-4511-9729-bf6f916bfce5.png)

**Comment by steakhal** [comment]
How does the plugin handle the case when I make frequent changes to a single but large file - where an analysis would take about 5 minutes?
It would always cancel the analysis it fired, would it?
How should the plugin behave in such a scenario?
One option could be to manually disable the _analysis on save_  and trigger the analysis manually or alternatively have a `debounce` time option. If you were storing the last successful analysis time of a given file, you could say that the plugin will only analyze the file if that's idle for 10% of the time required by an estimated successful analysis. For the files we have not analyzed yet we could have concrete seconds or something similar. For the rest, it would scale nicely.
WDYT?

**Comment by csordasmarton** [comment]
As far as I know this use case is handled and it will stop the previous analysis if you start a new analysis (e.g: saving your file). By the way @Discookie knows more about it.

**Comment by Discookie** [comment]
The way it currently works is that it doesn't kill off the analysis in progress, but instead queues a new one, and waits for the current one to finish.
The queue is always prepended with new entries - when you switch to a new file and save, the new file's analysis will be queued first.
When you cancel an analysis, it purges the entire queue.
AFAIK there's any deduplication on the queued analyses, that's certainly something to improve.

**Comment by steakhal** [comment]
@Discookie the Q approach won't work generally. Users might have other tools triggered on saves, which they want to use frequently.
For example, I have `clang-format` which prettifies my code whenever I save it. Such tools might advocate users to save more frequently than you would expect. Other than that what's the benefit of queuing these actions?
Since we can only assume that the latest state is consistent with the rest of the files such as multiple header files etc.
Are the entries in the queue any different than each other (for a given translation unit)? Since I'm not changing the `compilation_database`, I would expect them to be the exact same invocations.
