### ISSUE TITLE
Support for CodeChecker skipfiles

### ISSUE THREAD

**Issue by Discookie** [Ericsson/CodecheckerVSCodePlugin#74]
Currently, the ``Analyze current file`` command uses ``CodeChecker analyze --file``, which is incompatible with `--skip`.
So if a user specifies a skipfile argument (for a full project analysis), CodeChecker will error out on a single-file analysis.

If support is added, single-file analysis should also respect the skipfile.

**Comment by csordasmarton** [comment]
This problem has to be solved in CodeChecker and we already have a ticket for it: https://github.com/Ericsson/codechecker/issues/3595
