### ISSUE TITLE
The plugin is not listed among the Theia editor extensions

### ISSUE THREAD

**Issue by dkrupp** [Ericsson/CodecheckerVSCodePlugin#79]
Even though the plugin is published on openvsx https://open-vsx.org/extension/codechecker/codechecker
it is not listed among the Theia plugins using the latest Theia editor on Linux
https://www.eclipse.org/downloads/download.php?file=/theia/latest/linux/TheiaBlueprint.AppImage&r=1

**Comment by csordasmarton** [comment]
I think the problem will be the VSCode API version.

Our minimal supported VSCode API version is `1.55.0`:
https://github.com/Ericsson/CodecheckerVSCodePlugin/blob/e4eb7bf2476b1fa1901d5c04ed355830e48a34b5/package.json#L19

The latest Theia version supports only `1.53.2`:
https://github.com/eclipse-theia/theia/blob/3c13794abc58ad1b7c86a6727416863a72bae253/dev-packages/application-package/src/api.ts#L21

![image](https://user-images.githubusercontent.com/6695818/153413008-09eca290-2083-4b9b-b5c7-fef17ce5759b.png)

We have to check whether we can decrease our minimum VSCode API version to `1.53.2`.
