### ISSUE TITLE
The plugin goes into cyclic loop with clangd?

### ISSUE THREAD

**Issue by dkrupp** [Ericsson/CodecheckerVSCodePlugin#80]
Running analysis on file save causes cyclic interaction with the indexer based on the same compilation database file. The indexer (clangd) detects file as modified after Codechecker analysis. After further investigation it seems that the clangd picks up ${workspaceFolder}/.codechecker/compile_cmd.json and ${workspaceFolder}/.codechecker/unique_copmile_commands.json as additional indexing input (this is probably not a Codechecker issue). The solution is to NOT include codechecker output directory in the workspace. The reason indexer is triggered is known, but why would Codechecker also fall into a loop?

**Comment by Discookie** [comment]
I'll check Theia later, but using VSCode+WSL and VSCode+Linux, I couldn't reproduce this loop. Maybe this is Theia-specific as well?
